/**
 * Sails Seed Settings
 * (sails.config.seeds)
 *
 * Configuration for the data seeding in Sails.
 *
 * For more information on configuration, check out:
 * http://github.com/frostme/sails-seed
 */
module.exports.seeds = {
    user: [
        /*
        	.d8888. d888888b db    db d8888b. d88888b d8b   db d888888b .d8888.
        	88'  YP `~~88~~' 88    88 88  `8D 88'     888o  88 `~~88~~' 88'  YP
        	`8bo.      88    88    88 88   88 88ooooo 88V8o 88    88    `8bo.
        	  `Y8b.    88    88    88 88   88 88~~~~~ 88 V8o88    88      `Y8b.
        	db   8D    88    88b  d88 88  .8D 88.     88  V888    88    db   8D
        	`8888Y'    YP    ~Y8888P' Y8888D' Y88888P VP   V8P    YP    `8888Y'
        	
        	
        */

        {
            email: 'testuser1@test.com',
            password: 'testuser',
            firstName: 'Pranavan',
            lastName: 'Somaskandhan',

            phone: '+94771270555',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'pranavan',
            linksLinkedin: 'pranavan',
            linksStackoverflow: 'pranavan',
            linksGithub: 'pranavan',
            linksPortfolio: 'www.webportfolio1.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser2@test.com',
            password: 'testuser',
            firstName: 'Chamini',
            lastName: 'Prashakthi Perera',

            phone: '+94712286533',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'chamini',
            linksLinkedin: 'chamini',
            linksStackoverflow: 'chamini',
            linksGithub: 'chamini',
            linksPortfolio: 'www.webportfolio2.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser3@test.com',
            password: 'testuser',
            firstName: 'Udeni',
            lastName: 'Balasooriya',

            phone: '+94712045912',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'udeni',
            linksLinkedin: 'udeni',
            linksStackoverflow: 'udeni',
            linksGithub: 'udeni',
            linksPortfolio: 'www.webportfolio3.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser4@test.com',
            password: 'testuser',
            firstName: 'R',
            lastName: 'M.S.K. Chamodani',

            phone: '+94715492854',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'r',
            linksLinkedin: 'r',
            linksStackoverflow: 'r',
            linksGithub: 'r',
            linksPortfolio: 'www.webportfolio4.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser5@test.com',
            password: 'testuser',
            firstName: 'Keerthanan',
            lastName: 'Pathmanathan',

            phone: '+94779863425',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'keerthanan',
            linksLinkedin: 'keerthanan',
            linksStackoverflow: 'keerthanan',
            linksGithub: 'keerthanan',
            linksPortfolio: 'www.webportfolio5.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser6@test.com',
            password: 'testuser',
            firstName: 'Nishen',
            lastName: 'Peiris',

            phone: '+94775328115',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'nishen',
            linksLinkedin: 'nishen',
            linksStackoverflow: 'nishen',
            linksGithub: 'nishen',
            linksPortfolio: 'www.webportfolio6.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser7@test.com',
            password: 'testuser',
            firstName: 'Lakshitha',
            lastName: 'Deshapriya',

            phone: '+94717696596',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'lakshitha',
            linksLinkedin: 'lakshitha',
            linksStackoverflow: 'lakshitha',
            linksGithub: 'lakshitha',
            linksPortfolio: 'www.webportfolio7.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        },

        {
            email: 'testuser8@test.com',
            password: 'testuser',
            firstName: 'Pahan',
            lastName: 'Madusha Siriwardene Silva',

            phone: '+94715499498',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'pahan',
            linksLinkedin: 'pahan',
            linksStackoverflow: 'pahan',
            linksGithub: 'pahan',
            linksPortfolio: 'www.webportfolio8.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser9@test.com',
            password: 'testuser',
            firstName: 'Prageeth',
            lastName: 'Wanigasekara',

            phone: '+94714382403',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'prageeth',
            linksLinkedin: 'prageeth',
            linksStackoverflow: 'prageeth',
            linksGithub: 'prageeth',
            linksPortfolio: 'www.webportfolio9.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser10@test.com',
            password: 'testuser',
            firstName: 'Chalaka',
            lastName: 'Chamupathi Sudusinghe',

            phone: '+94717156570',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'chalaka',
            linksLinkedin: 'chalaka',
            linksStackoverflow: 'chalaka',
            linksGithub: 'chalaka',
            linksPortfolio: 'www.webportfolio10.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser11@test.com',
            password: 'testuser',
            firstName: 'Leshan',
            lastName: 'Bashitha Wijegunawardana',

            phone: '+94775232749',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'leshan',
            linksLinkedin: 'leshan',
            linksStackoverflow: 'leshan',
            linksGithub: 'leshan',
            linksPortfolio: 'www.webportfolio11.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser12@test.com',
            password: 'testuser',
            firstName: 'M',
            lastName: 'S.Jayani Sumudini',

            phone: '+94767290763',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'm',
            linksLinkedin: 'm',
            linksStackoverflow: 'm',
            linksGithub: 'm',
            linksPortfolio: 'www.webportfolio12.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser13@test.com',
            password: 'testuser',
            firstName: 'Danoja',
            lastName: 'Dias',

            phone: '+94771160393',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'danoja',
            linksLinkedin: 'danoja',
            linksStackoverflow: 'danoja',
            linksGithub: 'danoja',
            linksPortfolio: 'www.webportfolio13.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser14@test.com',
            password: 'testuser',
            firstName: 'Ching',
            lastName: 'Shi',

            phone: '+94770186272',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'ching',
            linksLinkedin: 'ching',
            linksStackoverflow: 'ching',
            linksGithub: 'ching',
            linksPortfolio: 'www.webportfolio14.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser15@test.com',
            password: 'testuser',
            firstName: 'Kumara',
            lastName: 'H.G.S.P',

            phone: '+94715635811',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'kumara',
            linksLinkedin: 'kumara',
            linksStackoverflow: 'kumara',
            linksGithub: 'kumara',
            linksPortfolio: 'www.webportfolio15.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser16@test.com',
            password: 'testuser',
            firstName: 'Subhani',
            lastName: 'Munasinghe',

            phone: '+94713665955',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'subhani',
            linksLinkedin: 'subhani',
            linksStackoverflow: 'subhani',
            linksGithub: 'subhani',
            linksPortfolio: 'www.webportfolio16.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser17@test.com',
            password: 'testuser',
            firstName: 'Manamgoda',
            lastName: 'Gamage Thilina Richard Manamgoda',

            phone: '+94770445855',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'manamgoda',
            linksLinkedin: 'manamgoda',
            linksStackoverflow: 'manamgoda',
            linksGithub: 'manamgoda',
            linksPortfolio: 'www.webportfolio17.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        },

        {
            email: 'testuser18@test.com',
            password: 'testuser',
            firstName: 'Akila',
            lastName: 'Wickramarachchi',

            phone: '+94715469414',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'akila',
            linksLinkedin: 'akila',
            linksStackoverflow: 'akila',
            linksGithub: 'akila',
            linksPortfolio: 'www.webportfolio18.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser19@test.com',
            password: 'testuser',
            firstName: 'Brian',
            lastName: 'Udugama',

            phone: '+94777002310',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'brian',
            linksLinkedin: 'brian',
            linksStackoverflow: 'brian',
            linksGithub: 'brian',
            linksPortfolio: 'www.webportfolio19.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser20@test.com',
            password: 'testuser',
            firstName: 'Nalaka',
            lastName: 'Sameera Rajamanthri',

            phone: '+94779549919',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'nalaka',
            linksLinkedin: 'nalaka',
            linksStackoverflow: 'nalaka',
            linksGithub: 'nalaka',
            linksPortfolio: 'www.webportfolio20.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser21@test.com',
            password: 'testuser',
            firstName: 'Rajitha',
            lastName: 'Ramanayake',

            phone: '+94779184048',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'rajitha',
            linksLinkedin: 'rajitha',
            linksStackoverflow: 'rajitha',
            linksGithub: 'rajitha',
            linksPortfolio: 'www.webportfolio21.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser22@test.com',
            password: 'testuser',
            firstName: 'Ishani',
            lastName: 'Paranawithana',

            phone: '+94773460072',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'ishani',
            linksLinkedin: 'ishani',
            linksStackoverflow: 'ishani',
            linksGithub: 'ishani',
            linksPortfolio: 'www.webportfolio22.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser23@test.com',
            password: 'testuser',
            firstName: 'Ishan',
            lastName: 'Madhusanka',

            phone: '+94716451456',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'ishan',
            linksLinkedin: 'ishan',
            linksStackoverflow: 'ishan',
            linksGithub: 'ishan',
            linksPortfolio: 'www.webportfolio23.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser24@test.com',
            password: 'testuser',
            firstName: 'Asanka',
            lastName: 'Dhananjaya Kumara',

            phone: '+94713844248',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'asanka',
            linksLinkedin: 'asanka',
            linksStackoverflow: 'asanka',
            linksGithub: 'asanka',
            linksPortfolio: 'www.webportfolio24.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser25@test.com',
            password: 'testuser',
            firstName: 'Tharuka',
            lastName: 'Jayalath',

            phone: '+94712687005',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'tharuka',
            linksLinkedin: 'tharuka',
            linksStackoverflow: 'tharuka',
            linksGithub: 'tharuka',
            linksPortfolio: 'www.webportfolio25.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser26@test.com',
            password: 'testuser',
            firstName: 'Ruchira',
            lastName: 'Kulathunga',

            phone: '+94702109150',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'ruchira',
            linksLinkedin: 'ruchira',
            linksStackoverflow: 'ruchira',
            linksGithub: 'ruchira',
            linksPortfolio: 'www.webportfolio26.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser27@test.com',
            password: 'testuser',
            firstName: 'Deshan',
            lastName: 'Kalupahana',

            phone: '+94767609644',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'deshan',
            linksLinkedin: 'deshan',
            linksStackoverflow: 'deshan',
            linksGithub: 'deshan',
            linksPortfolio: 'www.webportfolio27.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        },

        {
            email: 'testuser28@test.com',
            password: 'testuser',
            firstName: 'Dulanja',
            lastName: 'Mallikarachchi',

            phone: '+94719457171',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'dulanja',
            linksLinkedin: 'dulanja',
            linksStackoverflow: 'dulanja',
            linksGithub: 'dulanja',
            linksPortfolio: 'www.webportfolio28.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser29@test.com',
            password: 'testuser',
            firstName: 'Lahiru',
            lastName: 'Wijewardana',

            phone: '+94712933664',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'lahiru',
            linksLinkedin: 'lahiru',
            linksStackoverflow: 'lahiru',
            linksGithub: 'lahiru',
            linksPortfolio: 'www.webportfolio29.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser30@test.com',
            password: 'testuser',
            firstName: 'Wehigaldeniye',
            lastName: 'Gedara Nadeesha Maduman Amarasinghe',

            phone: '+94712720582',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'wehigaldeniye',
            linksLinkedin: 'wehigaldeniye',
            linksStackoverflow: 'wehigaldeniye',
            linksGithub: 'wehigaldeniye',
            linksPortfolio: 'www.webportfolio30.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser31@test.com',
            password: 'testuser',
            firstName: 'Lahiru',
            lastName: 'Dilshan',

            phone: '+94713605178',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'lahiru',
            linksLinkedin: 'lahiru',
            linksStackoverflow: 'lahiru',
            linksGithub: 'lahiru',
            linksPortfolio: 'www.webportfolio31.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser32@test.com',
            password: 'testuser',
            firstName: 'Sanduni',
            lastName: 'Prasadi',

            phone: '+94717462532',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'sanduni',
            linksLinkedin: 'sanduni',
            linksStackoverflow: 'sanduni',
            linksGithub: 'sanduni',
            linksPortfolio: 'www.webportfolio32.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser33@test.com',
            password: 'testuser',
            firstName: 'Lakshitha',
            lastName: 'Madushan',

            phone: '+94713149383',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'lakshitha',
            linksLinkedin: 'lakshitha',
            linksStackoverflow: 'lakshitha',
            linksGithub: 'lakshitha',
            linksPortfolio: 'www.webportfolio33.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser34@test.com',
            password: 'testuser',
            firstName: 'Prabhashani',
            lastName: 'Mohotti',

            phone: '+94717342194',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'prabhashani',
            linksLinkedin: 'prabhashani',
            linksStackoverflow: 'prabhashani',
            linksGithub: 'prabhashani',
            linksPortfolio: 'www.webportfolio34.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser35@test.com',
            password: 'testuser',
            firstName: 'Nadith',
            lastName: 'Premaratne',

            phone: '+94771819075',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'nadith',
            linksLinkedin: 'nadith',
            linksStackoverflow: 'nadith',
            linksGithub: 'nadith',
            linksPortfolio: 'www.webportfolio35.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser36@test.com',
            password: 'testuser',
            firstName: 'Jayamine',
            lastName: 'Alupotha',

            phone: '+94710426996',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'jayamine',
            linksLinkedin: 'jayamine',
            linksStackoverflow: 'jayamine',
            linksGithub: 'jayamine',
            linksPortfolio: 'www.webportfolio36.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser37@test.com',
            password: 'testuser',
            firstName: 'Vimukthi',
            lastName: 'Perera',

            phone: '+94776716570',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'vimukthi',
            linksLinkedin: 'vimukthi',
            linksStackoverflow: 'vimukthi',
            linksGithub: 'vimukthi',
            linksPortfolio: 'www.webportfolio37.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        },

        {
            email: 'testuser38@test.com',
            password: 'testuser',
            firstName: 'Pavinaa',
            lastName: 'Thavapalan',

            phone: '+94770326744',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'pavinaa',
            linksLinkedin: 'pavinaa',
            linksStackoverflow: 'pavinaa',
            linksGithub: 'pavinaa',
            linksPortfolio: 'www.webportfolio38.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser39@test.com',
            password: 'testuser',
            firstName: 'Lahiru',
            lastName: 'Samaranayaka',

            phone: '+94711944501',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'lahiru',
            linksLinkedin: 'lahiru',
            linksStackoverflow: 'lahiru',
            linksGithub: 'lahiru',
            linksPortfolio: 'www.webportfolio39.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser40@test.com',
            password: 'testuser',
            firstName: 'Chalana',
            lastName: 'Gunasekara',

            phone: '+94771448624',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'chalana',
            linksLinkedin: 'chalana',
            linksStackoverflow: 'chalana',
            linksGithub: 'chalana',
            linksPortfolio: 'www.webportfolio40.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser41@test.com',
            password: 'testuser',
            firstName: 'Dhanika',
            lastName: 'Munasinghe',

            phone: '+94719633911',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'dhanika',
            linksLinkedin: 'dhanika',
            linksStackoverflow: 'dhanika',
            linksGithub: 'dhanika',
            linksPortfolio: 'www.webportfolio41.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser42@test.com',
            password: 'testuser',
            firstName: 'Suranjaya',
            lastName: 'Ihalagama',

            phone: '+94717030380',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'suranjaya',
            linksLinkedin: 'suranjaya',
            linksStackoverflow: 'suranjaya',
            linksGithub: 'suranjaya',
            linksPortfolio: 'www.webportfolio42.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser43@test.com',
            password: 'testuser',
            firstName: 'Gihan',
            lastName: 'Wijesinghe',

            phone: '+94712205977',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'gihan',
            linksLinkedin: 'gihan',
            linksStackoverflow: 'gihan',
            linksGithub: 'gihan',
            linksPortfolio: 'www.webportfolio43.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser44@test.com',
            password: 'testuser',
            firstName: 'Mayuri',
            lastName: 'Maheshika Illesinghe',

            phone: '+94774288566',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'mayuri',
            linksLinkedin: 'mayuri',
            linksStackoverflow: 'mayuri',
            linksGithub: 'mayuri',
            linksPortfolio: 'www.webportfolio44.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser45@test.com',
            password: 'testuser',
            firstName: 'Thilini',
            lastName: 'Dahanayaka',

            phone: '+94773964161',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'thilini',
            linksLinkedin: 'thilini',
            linksStackoverflow: 'thilini',
            linksGithub: 'thilini',
            linksPortfolio: 'www.webportfolio45.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser46@test.com',
            password: 'testuser',
            firstName: 'Thusitha',
            lastName: 'Wijerathne',

            phone: '+94717498143',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'thusitha',
            linksLinkedin: 'thusitha',
            linksStackoverflow: 'thusitha',
            linksGithub: 'thusitha',
            linksPortfolio: 'www.webportfolio46.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser47@test.com',
            password: 'testuser',
            firstName: 'Avindu',
            lastName: 'Dinushan Hendawitharana',

            phone: '+94713844722',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'avindu',
            linksLinkedin: 'avindu',
            linksStackoverflow: 'avindu',
            linksGithub: 'avindu',
            linksPortfolio: 'www.webportfolio47.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        },

        {
            email: 'testuser48@test.com',
            password: 'testuser',
            firstName: 'Malwanage',
            lastName: 'Dhanuka  Dilsan Gunarathne',

            phone: '+94711905761',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'malwanage',
            linksLinkedin: 'malwanage',
            linksStackoverflow: 'malwanage',
            linksGithub: 'malwanage',
            linksPortfolio: 'www.webportfolio48.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser49@test.com',
            password: 'testuser',
            firstName: 'Chamith',
            lastName: 'Wickramasinghe',

            phone: '+94789993672',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'chamith',
            linksLinkedin: 'chamith',
            linksStackoverflow: 'chamith',
            linksGithub: 'chamith',
            linksPortfolio: 'www.webportfolio49.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser50@test.com',
            password: 'testuser',
            firstName: 'Dinithi',
            lastName: 'Weerasekera',

            phone: '+94719726865',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'dinithi',
            linksLinkedin: 'dinithi',
            linksStackoverflow: 'dinithi',
            linksGithub: 'dinithi',
            linksPortfolio: 'www.webportfolio50.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser51@test.com',
            password: 'testuser',
            firstName: 'Amila',
            lastName: 'indrajith ukwattage',

            phone: '+94775455047',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'amila',
            linksLinkedin: 'amila',
            linksStackoverflow: 'amila',
            linksGithub: 'amila',
            linksPortfolio: 'www.webportfolio51.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser52@test.com',
            password: 'testuser',
            firstName: 'Sasitha',
            lastName: 'Iresha',

            phone: '+94718282630',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'sasitha',
            linksLinkedin: 'sasitha',
            linksStackoverflow: 'sasitha',
            linksGithub: 'sasitha',
            linksPortfolio: 'www.webportfolio52.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser53@test.com',
            password: 'testuser',
            firstName: 'Charana',
            lastName: 'Udugama',

            phone: '+94713586994',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'charana',
            linksLinkedin: 'charana',
            linksStackoverflow: 'charana',
            linksGithub: 'charana',
            linksPortfolio: 'www.webportfolio53.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser54@test.com',
            password: 'testuser',
            firstName: 'Asanka',
            lastName: 'Ekanayake',

            phone: '+94712361254',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'asanka',
            linksLinkedin: 'asanka',
            linksStackoverflow: 'asanka',
            linksGithub: 'asanka',
            linksPortfolio: 'www.webportfolio54.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser55@test.com',
            password: 'testuser',
            firstName: 'Hasra',
            lastName: 'Dodampegama',

            phone: '+94717767074',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'hasra',
            linksLinkedin: 'hasra',
            linksStackoverflow: 'hasra',
            linksGithub: 'hasra',
            linksPortfolio: 'www.webportfolio55.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser56@test.com',
            password: 'testuser',
            firstName: 'Thushani',
            lastName: 'Nipunika',

            phone: '+94775803676',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'thushani',
            linksLinkedin: 'thushani',
            linksStackoverflow: 'thushani',
            linksGithub: 'thushani',
            linksPortfolio: 'www.webportfolio56.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser57@test.com',
            password: 'testuser',
            firstName: 'Rosen',
            lastName: 'Silva',

            phone: '+94770677418',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'rosen',
            linksLinkedin: 'rosen',
            linksStackoverflow: 'rosen',
            linksGithub: 'rosen',
            linksPortfolio: 'www.webportfolio57.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        },

        {
            email: 'testuser58@test.com',
            password: 'testuser',
            firstName: 'Asela',
            lastName: 'Dasanayaka',

            phone: '+94726655673',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'asela',
            linksLinkedin: 'asela',
            linksStackoverflow: 'asela',
            linksGithub: 'asela',
            linksPortfolio: 'www.webportfolio58.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser59@test.com',
            password: 'testuser',
            firstName: 'Darshi',
            lastName: 'Udurawana',

            phone: '+94714888393',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'darshi',
            linksLinkedin: 'darshi',
            linksStackoverflow: 'darshi',
            linksGithub: 'darshi',
            linksPortfolio: 'www.webportfolio59.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser60@test.com',
            password: 'testuser',
            firstName: 'manori',
            lastName: 'priyadarshani',

            phone: '+94712683021',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'manori',
            linksLinkedin: 'manori',
            linksStackoverflow: 'manori',
            linksGithub: 'manori',
            linksPortfolio: 'www.webportfolio60.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser61@test.com',
            password: 'testuser',
            firstName: 'Seralahthan',
            lastName: 'Vivekaananthan',

            phone: '+94779492296',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'seralahthan',
            linksLinkedin: 'seralahthan',
            linksStackoverflow: 'seralahthan',
            linksGithub: 'seralahthan',
            linksPortfolio: 'www.webportfolio61.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser62@test.com',
            password: 'testuser',
            firstName: 'Miyuru',
            lastName: 'Rajapaksha',

            phone: '+94774115037',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'miyuru',
            linksLinkedin: 'miyuru',
            linksStackoverflow: 'miyuru',
            linksGithub: 'miyuru',
            linksPortfolio: 'www.webportfolio62.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser63@test.com',
            password: 'testuser',
            firstName: 'indika',
            lastName: 'kumara',

            phone: '+94714909341',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'indika',
            linksLinkedin: 'indika',
            linksStackoverflow: 'indika',
            linksGithub: 'indika',
            linksPortfolio: 'www.webportfolio63.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser64@test.com',
            password: 'testuser',
            firstName: 'Priyankara',
            lastName: 'Bandara',

            phone: '+94711536783',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'priyankara',
            linksLinkedin: 'priyankara',
            linksStackoverflow: 'priyankara',
            linksGithub: 'priyankara',
            linksPortfolio: 'www.webportfolio64.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser65@test.com',
            password: 'testuser',
            firstName: 'Sriyan',
            lastName: 'Fernando',

            phone: '+94722079107',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'sriyan',
            linksLinkedin: 'sriyan',
            linksStackoverflow: 'sriyan',
            linksGithub: 'sriyan',
            linksPortfolio: 'www.webportfolio65.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser66@test.com',
            password: 'testuser',
            firstName: 'Dinidu',
            lastName: 'Weerakoon',

            phone: '+94755542297',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'dinidu',
            linksLinkedin: 'dinidu',
            linksStackoverflow: 'dinidu',
            linksGithub: 'dinidu',
            linksPortfolio: 'www.webportfolio66.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        }, {
            email: 'testuser67@test.com',
            password: 'testuser',
            firstName: 'Test',
            lastName: 'Student',

            phone: '+94812390000',
            birthDay: '',
            birthYear: 1992,
            photo: '',
            linksFacebook: 'test',
            linksLinkedin: 'test',
            linksStackoverflow: 'test',
            linksGithub: 'test',
            linksPortfolio: 'www.webportfolio67.com',
            isStudent: true,
            isAdmin: '',
            isOrganizationRep: '',
            // studentDetails: '',
            // organizationRepDetails: '',

        },
    ],

    /*
         .d88b.  d8888b.  d888b   .d8b.  d8b   db d888888b d88888D  .d8b.  d888888b d888888b  .d88b.  d8b   db .d8888.
        .8P  Y8. 88  `8D 88' Y8b d8' `8b 888o  88   `88'   YP  d8' d8' `8b `~~88~~'   `88'   .8P  Y8. 888o  88 88'  YP
        88    88 88oobY' 88      88ooo88 88V8o 88    88       d8'  88ooo88    88       88    88    88 88V8o 88 `8bo.
        88    88 88`8b   88  ooo 88~~~88 88 V8o88    88      d8'   88~~~88    88       88    88    88 88 V8o88   `Y8b.
        `8b  d8' 88 `88. 88. ~8~ 88   88 88  V888   .88.    d8' db 88   88    88      .88.   `8b  d8' 88  V888 db   8D
         `Y88P'  88   YD  Y888P  YP   YP VP   V8P Y888888P d88888P YP   YP    YP    Y888888P  `Y88P'  VP   V8P `8888Y'


    */

    organization: [{
        organizationName: 'Square Mobile',
        organizationAddress: 'No 410/33, Bauddhaloka Mawatha, Colombo 7',
        organizationPhone: '(011) 454 5720',
        organizationEmail: 'asanka@sqrmobile.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: 'https://github.com/Square-Mobile',
        linksWebpage: 'http://getshoutout.com',
        internsNeeded: 2,
    }, {
        organizationName: 'The Software Practice Pte Ltd',
        organizationAddress: 'Colombo',
        organizationPhone: '(065) 677 7798',
        organizationEmail: 'khasali@thesoftwarepractice.com',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/the-software-practice-pte-ltd',
        linksGithub: ' ',
        linksWebpage: 'http://thesoftwarepractice.com',
        internsNeeded: 4,
    }, {
        organizationName: 'Millennium IT - Enterprise Service',
        organizationAddress: 'Colombo',
        organizationPhone: '(011) 241 6000',
        organizationEmail: 'srilalbuddika@gmail.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 2,
    }, {
        organizationName: 'hSenid Mobile',
        organizationAddress: 'Colombo',
        organizationPhone: '(011) 268 3751',
        organizationEmail: 'kalhara@hsenid.com',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/hsenid-mobile-solutions-pvt-ltd',
        linksGithub: ' ',
        linksWebpage: 'https://www.hsenidmobile.com',
        internsNeeded: 3,
    }, {
        organizationName: 'Interblocks Ltd',
        organizationAddress: 'Level 2, 240, Highlevel Road, Colombo 00600, Sri Lanka.   http://www.interblocks.com',
        organizationPhone: '(070) 300 3380',
        organizationEmail: 'gayani.w@interblocks.com',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/interblocks-ltd',
        linksGithub: ' ',
        linksWebpage: 'www.interblocks.com',
        internsNeeded: 1,
    }, {
        organizationName: 'SimCentric Technolgoies (pvt) Ltd',
        organizationAddress: ' ',
        organizationPhone: '(011) 436 8968',
        organizationEmail: 'piyumanthika@simct.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 0,
    }, {
        organizationName: 'IFS R&D International (private) limited',
        organizationAddress: '501 Galle Road, Colombo 6, Sri Lanka',
        organizationPhone: '(011) 236 4400',
        organizationEmail: 'kandasamy.yogendirakumar@ifsworld.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: 'http://www.ifsworld.com/lk',
        internsNeeded: 4,
    }, {
        organizationName: 'Unicorn solutions (Pvt) Ltd',
        organizationAddress: '21/8A, Chandra Silva Mw, Pagoda Road , Nugegoda',
        organizationPhone: '(011) 739 3780',
        organizationEmail: 'priyantha@unicorn-solutions.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 2,
    }, {
        organizationName: 'Just in Time Group',
        organizationAddress: 'Colombo 03',
        organizationPhone: '(077) 379 3717',
        organizationEmail: 'dillon@jithpl.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 10,
    }, {
        organizationName: 'Pulz Technologies pvt Ltd',
        organizationAddress: 'Colombo 07',
        organizationPhone: '(011) 266 5100',
        organizationEmail: 'hr@pulztec.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: 'www.pulztec.com',
        internsNeeded: 4,
    }, {
        organizationName: 'CAMMS',
        organizationAddress: 'CAMMS, Level 13, East Tower, World Trade Centre, Echelon Square, Colombo 01',
        organizationPhone: '(077) 719 0655',
        organizationEmail: 'Sukith.Nanayakkara@cammsgroup.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 5,
    }, {
        organizationName: 'DirectFN | Mubasher',
        organizationAddress: 'D F N Technology (Pvt) Ltd (DirectFN) No. 33, Park Street, Level 10, Parkland, Col-02. Tel: 0112307311 & Mubasher Technologies (Pvt) Ltd (Mubasher) No. 19, 6th Flr, Browns Capital Building, Dudley Senanayake Mw, Col-08. Tel: 0112680585',
        organizationPhone: '(011) 230 7311',
        organizationEmail: 'h.satheeq@directfn.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: 'http://www.directfn.com/ | http://www.mubashertrade.com',
        internsNeeded: 3,
    }, {
        organizationName: 'Zone 24x7 (Pvt) Ltd',
        organizationAddress: '460, Nawala Road, Koswatte, Sri Lanka 10107',
        organizationPhone: '(077) 733 7072',
        organizationEmail: 'sudeshis@zone24x7.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 3,
    }, {
        organizationName: 'WSO2',
        organizationAddress: 'No. 20, Palm Grove, Colombo 03',
        organizationPhone: '(077) 767 0410',
        organizationEmail: 'pramila@wso2.com',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/wso2',
        linksGithub: 'https://github.com/wso2',
        linksWebpage: 'http://www.wso2.org',
        internsNeeded: 6,
    }, {
        organizationName: 'CodeGen International (Pvt) Ltd',
        organizationAddress: 'Bay No : 1 - 5, TRACE Expert City, Tripoli Market Square, Maradana',
        organizationPhone: '(000) 000 0000',
        organizationEmail: 'roshanj@codegen.net',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 3,
    }, {
        organizationName: 'IBM',
        organizationAddress: '48, Nawam Mawatha, Colombo 2',
        organizationPhone: '(077) 399 2594',
        organizationEmail: 'mark@lk.ibm.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 4,
    }, {
        organizationName: 'Synopsys',
        organizationAddress: 'No 3, 2/1 Lukshmi Gardens Colombo 8',
        organizationPhone: '(011) 203 8621',
        organizationEmail: 'farazyf@synopsys.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: 'www.synopsys.com',
        internsNeeded: 1,
    }, {
        organizationName: 'TechCERT',
        organizationAddress: '1st Floor, Bernards Business Park, 106, Dutugemunu Street, Dehiwala, 10350',
        organizationPhone: '(011) 446 2500',
        organizationEmail: 'harshana@techcert.lk',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 2,
    }, {
        organizationName: 'VirtusaPolaris',
        organizationAddress: ' ',
        organizationPhone: '(077) 738 2266',
        organizationEmail: 'nacassim@virtusapolaris.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 0,
    }, {
        organizationName: 'Pearson',
        organizationAddress: ' ',
        organizationPhone: '(077) 784 1120',
        organizationEmail: 'mathuri.srirohanan@pearson.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 0,
    }, {
        organizationName: 'ShipXpress Technologies (Private) Limited',
        organizationAddress: '247 1/2, Stanley Thilakarathna Mawatha, Nugegoda',
        organizationPhone: '(011) 282 6814',
        organizationEmail: 'shehani.perera@shipxpress.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 2,
    }, {
        organizationName: 'OrangeHRM',
        organizationAddress: '29/15A, Visaka Road, Colombo 04, Sri Lanka',
        organizationPhone: '(077) 612 1846',
        organizationEmail: 'nuwan@orangehrm.us.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: 'https://www.orangehrm.com',
        internsNeeded: 2,
    }, {
        organizationName: 'KBSL Information Technologies Limited',
        organizationAddress: '297 Union Pl, Colombo',
        organizationPhone: '(071) 775 0754',
        organizationEmail: 'kaushala@kbsl.lk',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/keells-business-systems-limited',
        linksGithub: ' ',
        linksWebpage: 'http://www.kbslit.com',
        internsNeeded: 2,
    }, {
        organizationName: 'N able',
        organizationAddress: 'Bristol St, Colombo 00100',
        organizationPhone: '(077) 040 9274',
        organizationEmail: 'nimali@n-able.biz',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/n-able-private-limite',
        linksGithub: ' ',
        linksWebpage: 'www.n-able.biz',
        internsNeeded: 1,
    }, {
        organizationName: 'LankaCom',
        organizationAddress: ' 65 C, Dharmapala Mawatha,, Colombo 00700',
        organizationPhone: '(011) 243 7545',
        organizationEmail: 'supunr@lankacom.net',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/in/lanka-com-37736b44',
        linksGithub: ' ',
        linksWebpage: 'http://www.lankacom.net',
        internsNeeded: 2,
    }, {
        organizationName: 'MillenniumIT',
        organizationAddress: 'No. 1, Millennium Drive, Malabe',
        organizationPhone: '(076) 871 3028',
        organizationEmail: 'pavanr@millenniumit.com',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/30209?trk=tyah&trkInfo=tas%3Amillenniumit%2Cidx%3A1-1-1',
        linksGithub: ' ',
        linksWebpage: 'http://www.millenniumit.com',
        internsNeeded: 7,
    }, {
        organizationName: 'VirtusaPolaris',
        organizationAddress: ' ',
        organizationPhone: '(077) 738 2266',
        organizationEmail: 'campusreachsl@virtusapolaris.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 0,
    }, {
        organizationName: 'Pearson Lanka (Pvt) Ltd',
        organizationAddress: ' ',
        organizationPhone: '(011) 273 8848',
        organizationEmail: 'mathuri.sr@gmail.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 0,
    }, {
        organizationName: 'Omobio Pvt. Ltd',
        organizationAddress: '1, St. Albans Place, Colombo 4',
        organizationPhone: '(077) 340 0639',
        organizationEmail: 'hakimafalul@gmail.com',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/omobio-pvt-ltd',
        linksGithub: ' ',
        linksWebpage: 'http://www.omobio.net',
        internsNeeded: 10,
    }, {
        organizationName: 'The Software Practice Pte Ltd',
        organizationAddress: 'Mount Lavinia',
        organizationPhone: '(071) 142 6411',
        organizationEmail: 'nemina@thesoftwarepractice.com',
        linksFacebook: ' ',
        linksLinkedin: 'https://www.linkedin.com/company/the-software-practice-pte-ltd',
        linksGithub: ' ',
        linksWebpage: 'http://www.thesoftwarepractice.com',
        internsNeeded: 4,
    }, {
        organizationName: 'Versatile Integrated Global Operations (pvt) Ltd',
        organizationAddress: '224B, Galvihara Road, Dehiwala',
        organizationPhone: '(077) 756 8935',
        organizationEmail: 'chanaranga@viglobaloperations.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 4,
    }, {
        organizationName: 'CAM Management Solutions (Pvt) Limited',
        organizationAddress: ' ',
        organizationPhone: '(011) 544 3443',
        organizationEmail: 'careers@cammsgroup.com',
        linksFacebook: ' ',
        linksLinkedin: ' ',
        linksGithub: ' ',
        linksWebpage: ' ',
        internsNeeded: 0,
    }]
}